### ISSUE TITLE
Make KeyValue parameters pass by values and forward them in

### ISSUE THREAD

**Issue by Andrew-Hill-SpotX** [jbaldwin/libcappuccino#13]
The functions taking the KeyValue type ought to take them by value as a parameter. From that point we can forward them into the internal functions. This will potentially remove unnecessary copies if the user of the API provides us an rvalue KeyType that we end up storing internally.

**Comment by jbaldwin** [comment]
I think maybe they should be universal references with std::forward?

**Comment by Andrew-Hill-SpotX** [comment]
I think I meant to say the KeyType parameters(for the Insert functions for example) oughta be l-value params and then moved in to prevent a copy. I don't know what I was thinking about forward? Forward doesn't seem appropriate here because most the functions aren't templated(beyond the class itself being templated)

**Comment by jbaldwin** [comment]
I feel like this might actually be suboptimal? As it would force a copy on every `insert` where it might not be needed if the call is an `update`.  In that case the copy can be elided.  However if we force by value+move then in that case the copy on the key is unneeded, whereas now with `const& key_type` it will only take a copy of the key if is actually inserted into the data structure.

I think on a true `insert` where you know the `key`doesn't exist, it would be best if it could be moved in, but I'm not sure how to do that without splitting the `insert()` function into two, one `insert()` and one `update()`.  I dislike this change because its signficantly nicer to be able to allow for the `update` to happen (if desired) on the same call without having to waste another lock + `update()` call to update the value in the cache after the `insert()` fails.

**Comment by Andrew-Hill-SpotX** [comment]
Here is a rough translation from Kevin how we can accomplish this via perfect forward as you suggested
`template<typename T>
class MyT
{
    template <typename V>
    void func(V&& v)
    {
        static_assert(std::is_same<std::decay_t<V>, T>::value, "Argument to func must be of container value type");
        some_other_funct(std::forward<V>(v)):
    }
};`

**Comment by kevin-logan** [comment]
after thinking about it I didn't like the assert using std::decay_t<V> since that could cause the check to never pass when the class template type (T above) is a reference type. I checked what std::optional was doing for it's forwarding assignment operator and among other unrelated things, they basically check:
`std::is_constructible<T, V>::value && std::is_assignable<T&, V>::value`
so I think it would be more appropriate for us to do something similar.
